### ISSUE TITLE
incorrect atrribute name for xinetd service template

### ISSUE THREAD

**Issue by stgarf** [stevendanna/cookbook-xinetd#7]
I noticed a service wasn't getting disabled when I set disabled to yes.

In `/var/log/syslog.log` I can see the following:
> Jan 21 00:06:49 debian-7 xinetd[3643]: bad service attribute: disabled [file=/etc/xinetd.d/http [line=3]

https://github.com/stevendanna/cookbook-xinetd/blob/master/templates/default/service.erb#L3

I believe the correct atrribute name is actually `disable` as opposed to it's current incarnation.

Setting disable = yes successfully disabled the service in xinetd for me on this system.

**Comment by stgarf** [comment]
On thing that I hadn't considered was this was was renamed or differs based on xinetd version. I have not looked into this, nor have I tested it.

**Comment by stevendanna** [comment]
1.0.2 has ben released which should have your fix.  Thanks!
